version: '3'

networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
    networks:
      - dev

  backend:
    build:
      context: .
    networks:
      - dev
