# Generated by Django 4.2.16 on 2024-12-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0007_alter_customuser_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Doctor', 'Доктор'), ('User', 'Пользователь')], default='User', max_length=20, verbose_name='Роль'),
        ),
    ]
